dependencies:
- name:  mariadb
  version: 0.6.3
  repository: https://kubernetes-charts.storage.googleapis.com/
- name:  redis
  version: 0.7.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name:  rabbitmq
  version: 0.5.3
  repository: https://kubernetes-charts.storage.googleapis.com/
