dataflowUsername: user
dataflowPassword: password
dataflowRoles: ROLE_VIEW, ROLE_CREATE
dataflowAdminUsername: admin
dataflowAdminPassword: admin
dataflowAdminRoles: ROLE_MANAGE, ROLE_VIEW
server:
  version: 1.2.0.RELEASE
metrics:
  version: 1.0.0.RELEASE
rabbitmq:
  rabbitmqUsername: user
mysql:
  mysqlDatabase: dataflow
