apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-server
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}-server
    spec:
      containers:
      - name: {{ template "fullname" . }}-server
        image: springcloud/spring-cloud-dataflow-server-kubernetes:{{ .Values.server.version }}
        imagePullPolicy: Always
        volumeMounts: [
          {
            name: rabbitmq,
            mountPath: /etc/secrets/rabbitmq,
            readOnly: true
          },
          {
            name: mysql,
            mountPath: /etc/secrets/mysql,
            readOnly: true
          },
          {
            name: redis,
            mountPath: /etc/secrets/redis,
            readOnly: true
          }
        ]
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1.0
            memory: 2048Mi
          requests:
            cpu: 0.5
            memory: 1024Mi
        livenessProbe:
          httpGet:
            path: /management/health
            port: 80
            httpHeaders:
            - name: Authorization
              value: 'Basic {{ printf "%s:%s" .Values.dataflowAdminUsername .Values.dataflowAdminPassword | b64enc }}'
          initialDelaySeconds: 120
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /management/health
            port: 80
            httpHeaders:
            - name: Authorization
              value: 'Basic {{ printf "%s:%s" .Values.dataflowAdminUsername .Values.dataflowAdminPassword | b64enc }}'
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: SERVER_PORT
          value: '80'
        - name: SPRING_CLOUD_CONFIG_SERVER_BOOTSTRAP
          value: 'false'
        - name: SPRING_CLOUD_DATAFLOW_FEATURES_ANALYTICS_ENABLED
          value: 'true'
        - name: SPRING_CLOUD_DEPLOYER_KUBERNETES_MEMORY
          value: 640Mi
        - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
          value: {{ template "fullname" . }}-server
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
          value: 'true'
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_PATHS
          value: /etc/secrets
        - name: SPRING_CLOUD_DATAFLOW_METRICS_COLLECTOR_URI
          value: 'http://${{ printf "{%s" .Release.Name | upper }}_SPRING_CLOUD_DATA_FLOW_METRICS_SERVICE_HOST}'
        - name: SPRING_CLOUD_DATAFLOW_SERVER_URI
          value: 'http://${{ printf "{%s" .Release.Name | upper }}_SPRING_CLOUD_DATA_FLOW_SERVER_SERVICE_HOST}:${{ printf "{%s" .Release.Name | upper }}_SPRING_CLOUD_DATA_FLOW_SERVER_SERVICE_PORT}'
          # Maven repo for metadata artifact resolution plus metrics destination for all stream apps
        - name: SPRING_APPLICATION_JSON
          value: "{ \"maven\": { \"local-repository\": null, \"remote-repositories\": { \"repo1\": { \"url\": \"https://repo.spring.io/libs-snapshot\"} } }, \"spring.cloud.dataflow.application-properties.stream.spring.cloud.stream.bindings.applicationMetrics.destination\": \"metrics\" }"
      volumes: [
        {
          name: rabbitmq,
          secret: {
            secretName: {{ printf "%s-%s" .Release.Name "rabbitmq" | trunc 63 | trimSuffix "-" }}
          }
        },
        {
          name: mysql,
          secret: {
            secretName: {{ printf "%s-%s" .Release.Name "mysql" | trunc 63 | trimSuffix "-" }}
          }
        },
        {
          name: redis,
          secret: {
            secretName: {{ printf "%s-%s" .Release.Name "redis" | trunc 63 | trimSuffix "-" }}
          }
        }
      ]
